language: node_js
node_js:
  - "9"
dist: trusty
sudo: false

branches:
  only:
  - master

before_script:
  - npm install -g @angular/cli@7.2

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - ng build --prod --base-href https://niawjunior.github.io/blog/
  - mv dist/browser/index.html dist/browser/404.html

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/browser
  on:
    branch: master
